// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: fcd9ff140d
// Version Date: 2021-07-14T06:36:40Z

package svc

// This file contains methods to make individual endpoints from services,
// request and response types to serve those endpoints, as well as encoders and
// decoders for those types, for all of our supported transport serialization
// formats.

import (
	"context"
	"fmt"

	"github.com/go-kit/kit/endpoint"

	pb "github.com/vpiyush/go-kit-truss"
)

// Endpoints collects all of the endpoints that compose an add service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
//
// In a server, it's useful for functions that need to operate on a per-endpoint
// basis. For example, you might pass an Endpoints to a function that produces
// an http.Handler, with each method (endpoint) wired up to a specific path. (It
// is probably a mistake in design to invoke the Service methods on the
// Endpoints struct in a server.)
//
// In a client, it's useful to collect individually constructed endpoints into a
// single type that implements the Service interface. For example, you might
// construct individual endpoints using transport/http.NewClient, combine them into an Endpoints, and return it to the caller as a Service.
type Endpoints struct {
	GetDocumentEndpoint endpoint.Endpoint
	AddDocumentEndpoint endpoint.Endpoint
	WatermarkEndpoint   endpoint.Endpoint
}

// Endpoints

func (e Endpoints) GetDocument(ctx context.Context, in *pb.GetDocumentRequest) (*pb.GetDocumentResponse, error) {
	response, err := e.GetDocumentEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.GetDocumentResponse), nil
}

func (e Endpoints) AddDocument(ctx context.Context, in *pb.AddDocumentRequest) (*pb.AddDocumentResponse, error) {
	response, err := e.AddDocumentEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.AddDocumentResponse), nil
}

func (e Endpoints) Watermark(ctx context.Context, in *pb.WatermarkRequest) (*pb.WatermarkResponse, error) {
	response, err := e.WatermarkEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.WatermarkResponse), nil
}

// Make Endpoints

func MakeGetDocumentEndpoint(s pb.WatermarkServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.GetDocumentRequest)
		v, err := s.GetDocument(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeAddDocumentEndpoint(s pb.WatermarkServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.AddDocumentRequest)
		v, err := s.AddDocument(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeWatermarkEndpoint(s pb.WatermarkServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.WatermarkRequest)
		v, err := s.Watermark(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

// WrapAllExcept wraps each Endpoint field of struct Endpoints with a
// go-kit/kit/endpoint.Middleware.
// Use this for applying a set of middlewares to every endpoint in the service.
// Optionally, endpoints can be passed in by name to be excluded from being wrapped.
// WrapAllExcept(middleware, "Status", "Ping")
func (e *Endpoints) WrapAllExcept(middleware endpoint.Middleware, excluded ...string) {
	included := map[string]struct{}{
		"GetDocument": {},
		"AddDocument": {},
		"Watermark":   {},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc := range included {
		if inc == "GetDocument" {
			e.GetDocumentEndpoint = middleware(e.GetDocumentEndpoint)
		}
		if inc == "AddDocument" {
			e.AddDocumentEndpoint = middleware(e.AddDocumentEndpoint)
		}
		if inc == "Watermark" {
			e.WatermarkEndpoint = middleware(e.WatermarkEndpoint)
		}
	}
}

// LabeledMiddleware will get passed the endpoint name when passed to
// WrapAllLabeledExcept, this can be used to write a generic metrics
// middleware which can send the endpoint name to the metrics collector.
type LabeledMiddleware func(string, endpoint.Endpoint) endpoint.Endpoint

// WrapAllLabeledExcept wraps each Endpoint field of struct Endpoints with a
// LabeledMiddleware, which will receive the name of the endpoint. See
// LabeldMiddleware. See method WrapAllExept for details on excluded
// functionality.
func (e *Endpoints) WrapAllLabeledExcept(middleware func(string, endpoint.Endpoint) endpoint.Endpoint, excluded ...string) {
	included := map[string]struct{}{
		"GetDocument": {},
		"AddDocument": {},
		"Watermark":   {},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc := range included {
		if inc == "GetDocument" {
			e.GetDocumentEndpoint = middleware("GetDocument", e.GetDocumentEndpoint)
		}
		if inc == "AddDocument" {
			e.AddDocumentEndpoint = middleware("AddDocument", e.AddDocumentEndpoint)
		}
		if inc == "Watermark" {
			e.WatermarkEndpoint = middleware("Watermark", e.WatermarkEndpoint)
		}
	}
}
