// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: fcd9ff140d
// Version Date: 2021-07-14T06:36:40Z

// Package grpc provides a gRPC client for the Watermark service.
package grpc

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/endpoint"
	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/vpiyush/go-kit-truss"
	"github.com/vpiyush/go-kit-truss/watermark-service/svc"
)

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, options ...ClientOption) (pb.WatermarkServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions := []grpctransport.ClientOption{
		grpctransport.ClientBefore(
			contextValuesToGRPCMetadata(cc.headers)),
	}
	var getdocumentEndpoint endpoint.Endpoint
	{
		getdocumentEndpoint = grpctransport.NewClient(
			conn,
			"watermark.Watermark",
			"GetDocument",
			EncodeGRPCGetDocumentRequest,
			DecodeGRPCGetDocumentResponse,
			pb.GetDocumentResponse{},
			clientOptions...,
		).Endpoint()
	}

	var adddocumentEndpoint endpoint.Endpoint
	{
		adddocumentEndpoint = grpctransport.NewClient(
			conn,
			"watermark.Watermark",
			"AddDocument",
			EncodeGRPCAddDocumentRequest,
			DecodeGRPCAddDocumentResponse,
			pb.AddDocumentResponse{},
			clientOptions...,
		).Endpoint()
	}

	var watermarkEndpoint endpoint.Endpoint
	{
		watermarkEndpoint = grpctransport.NewClient(
			conn,
			"watermark.Watermark",
			"Watermark",
			EncodeGRPCWatermarkRequest,
			DecodeGRPCWatermarkResponse,
			pb.WatermarkResponse{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		GetDocumentEndpoint: getdocumentEndpoint,
		AddDocumentEndpoint: adddocumentEndpoint,
		WatermarkEndpoint:   watermarkEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCGetDocumentResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC getdocument reply to a user-domain getdocument response. Primarily useful in a client.
func DecodeGRPCGetDocumentResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.GetDocumentResponse)
	return reply, nil
}

// DecodeGRPCAddDocumentResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC adddocument reply to a user-domain adddocument response. Primarily useful in a client.
func DecodeGRPCAddDocumentResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.AddDocumentResponse)
	return reply, nil
}

// DecodeGRPCWatermarkResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC watermark reply to a user-domain watermark response. Primarily useful in a client.
func DecodeGRPCWatermarkResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.WatermarkResponse)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCGetDocumentRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain getdocument request to a gRPC getdocument request. Primarily useful in a client.
func EncodeGRPCGetDocumentRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.GetDocumentRequest)
	return req, nil
}

// EncodeGRPCAddDocumentRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain adddocument request to a gRPC adddocument request. Primarily useful in a client.
func EncodeGRPCAddDocumentRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.AddDocumentRequest)
	return req, nil
}

// EncodeGRPCWatermarkRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain watermark request to a gRPC watermark request. Primarily useful in a client.
func EncodeGRPCWatermarkRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.WatermarkRequest)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
