// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: fcd9ff140d
// Version Date: 2021-07-14T06:36:40Z

// Package http provides an HTTP client for the Watermark service.
package http

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/gogo/protobuf/jsonpb"

	"github.com/go-kit/kit/endpoint"
	httptransport "github.com/go-kit/kit/transport/http"
	"github.com/pkg/errors"

	// This Service
	"github.com/go-kit/kit/circuitbreaker"
	"github.com/sony/gobreaker"
	pb "github.com/vpiyush/go-kit-truss"
	"github.com/vpiyush/go-kit-truss/watermark-service/svc"
)

var (
	_ = endpoint.Chain
	_ = httptransport.NewClient
	_ = fmt.Sprint
	_ = bytes.Compare
	_ = ioutil.NopCloser
	_ = io.EOF
)

// New returns a service backed by an HTTP server living at the remote
// instance. We expect instance to come from a service discovery system, so
// likely of the form "host:port".
func New(instance string, options ...httptransport.ClientOption) (pb.WatermarkServer, error) {

	if !strings.HasPrefix(instance, "http") {
		instance = "http://" + instance
	}
	u, err := url.Parse(instance)
	if err != nil {
		return nil, err
	}
	_ = u

	cbreaker := circuitbreaker.Gobreaker(gobreaker.NewCircuitBreaker(
		gobreaker.Settings{
			Name:    "GetDocument",
			Timeout: 30 * time.Second,
		}))
	var GetDocumentZeroEndpoint endpoint.Endpoint
	{
		GetDocumentZeroEndpoint = httptransport.NewClient(
			"GET",
			copyURL(u, "/document/"),
			EncodeHTTPGetDocumentZeroRequest,
			DecodeHTTPGetDocumentResponse,
			options...,
		).Endpoint()
		// circuitbreaker end poin
		GetDocumentZeroEndpoint = circuitbreaker.Gobreaker(gobreaker.NewCircuitBreaker(
			gobreaker.Settings{
				Name:    "GetDocument",
				Timeout: 30 * time.Second,
			},
		))(GetDocumentZeroEndpoint)
	}
	var AddDocumentZeroEndpoint endpoint.Endpoint
	{
		AddDocumentZeroEndpoint = httptransport.NewClient(
			"POST",
			copyURL(u, "/document/"),
			EncodeHTTPAddDocumentZeroRequest,
			DecodeHTTPAddDocumentResponse,
			options...,
		).Endpoint()
		AddDocumentZeroEndpoint = cbreaker(AddDocumentZeroEndpoint)
	}
	var WatermarkZeroEndpoint endpoint.Endpoint
	{
		WatermarkZeroEndpoint = httptransport.NewClient(
			"POST",
			copyURL(u, "/watermark/"),
			EncodeHTTPWatermarkZeroRequest,
			DecodeHTTPWatermarkResponse,
			options...,
		).Endpoint()
		WatermarkZeroEndpoint = cbreaker(WatermarkZeroEndpoint)
	}

	return svc.Endpoints{
		GetDocumentEndpoint: GetDocumentZeroEndpoint,
		AddDocumentEndpoint: AddDocumentZeroEndpoint,
		WatermarkEndpoint:   WatermarkZeroEndpoint,
	}, nil
}

func copyURL(base *url.URL, path string) *url.URL {
	next := *base
	next.Path = path
	return &next
}

// CtxValuesToSend configures the http client to pull the specified keys out of
// the context and add them to the http request as headers.  Note that keys
// will have net/http.CanonicalHeaderKey called on them before being send over
// the wire and that is the form they will be available in the server context.
func CtxValuesToSend(keys ...string) httptransport.ClientOption {
	return httptransport.ClientBefore(func(ctx context.Context, r *http.Request) context.Context {
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				r.Header.Set(k, v)
			}
		}
		return ctx
	})
}

// HTTP Client Decode

// DecodeHTTPGetDocumentResponse is a transport/http.DecodeResponseFunc that decodes
// a JSON-encoded GetDocumentResponse response from the HTTP response body.
// If the response has a non-200 status code, we will interpret that as an
// error and attempt to decode the specific error message from the response
// body. Primarily useful in a client.
func DecodeHTTPGetDocumentResponse(_ context.Context, r *http.Response) (interface{}, error) {
	defer r.Body.Close()
	buf, err := ioutil.ReadAll(r.Body)
	if err == io.EOF {
		return nil, errors.New("response http body empty")
	}
	if err != nil {
		return nil, errors.Wrap(err, "cannot read http body")
	}

	if r.StatusCode != http.StatusOK {
		return nil, errors.Wrapf(errorDecoder(buf), "status code: '%d'", r.StatusCode)
	}

	var resp pb.GetDocumentResponse
	if err = jsonpb.UnmarshalString(string(buf), &resp); err != nil {
		return nil, errorDecoder(buf)
	}

	return &resp, nil
}

// DecodeHTTPAddDocumentResponse is a transport/http.DecodeResponseFunc that decodes
// a JSON-encoded AddDocumentResponse response from the HTTP response body.
// If the response has a non-200 status code, we will interpret that as an
// error and attempt to decode the specific error message from the response
// body. Primarily useful in a client.
func DecodeHTTPAddDocumentResponse(_ context.Context, r *http.Response) (interface{}, error) {
	defer r.Body.Close()
	buf, err := ioutil.ReadAll(r.Body)
	if err == io.EOF {
		return nil, errors.New("response http body empty")
	}
	if err != nil {
		return nil, errors.Wrap(err, "cannot read http body")
	}

	if r.StatusCode != http.StatusOK {
		return nil, errors.Wrapf(errorDecoder(buf), "status code: '%d'", r.StatusCode)
	}

	var resp pb.AddDocumentResponse
	if err = jsonpb.UnmarshalString(string(buf), &resp); err != nil {
		return nil, errorDecoder(buf)
	}

	return &resp, nil
}

// DecodeHTTPWatermarkResponse is a transport/http.DecodeResponseFunc that decodes
// a JSON-encoded WatermarkResponse response from the HTTP response body.
// If the response has a non-200 status code, we will interpret that as an
// error and attempt to decode the specific error message from the response
// body. Primarily useful in a client.
func DecodeHTTPWatermarkResponse(_ context.Context, r *http.Response) (interface{}, error) {
	defer r.Body.Close()
	buf, err := ioutil.ReadAll(r.Body)
	if err == io.EOF {
		return nil, errors.New("response http body empty")
	}
	if err != nil {
		return nil, errors.Wrap(err, "cannot read http body")
	}

	if r.StatusCode != http.StatusOK {
		return nil, errors.Wrapf(errorDecoder(buf), "status code: '%d'", r.StatusCode)
	}

	var resp pb.WatermarkResponse
	if err = jsonpb.UnmarshalString(string(buf), &resp); err != nil {
		return nil, errorDecoder(buf)
	}

	return &resp, nil
}

// HTTP Client Encode

// EncodeHTTPGetDocumentZeroRequest is a transport/http.EncodeRequestFunc
// that encodes a getdocument request into the various portions of
// the http request (path, query, and body).
func EncodeHTTPGetDocumentZeroRequest(_ context.Context, r *http.Request, request interface{}) error {
	strval := ""
	_ = strval
	req := request.(*pb.GetDocumentRequest)
	_ = req

	r.Header.Set("transport", "HTTPJSON")
	r.Header.Set("request-url", r.URL.Path)

	// Set the path parameters
	path := strings.Join([]string{
		"",
		"document",
		"",
	}, "/")
	u, err := url.Parse(path)
	if err != nil {
		return errors.Wrapf(err, "couldn't unmarshal path %q", path)
	}
	r.URL.RawPath = u.RawPath
	r.URL.Path = u.Path

	// Set the query parameters
	values := r.URL.Query()
	var tmp []byte
	_ = tmp

	values.Add("Key", fmt.Sprint(req.Key))

	values.Add("Value", fmt.Sprint(req.Value))

	r.URL.RawQuery = values.Encode()
	return nil
}

// EncodeHTTPGetDocumentOneRequest is a transport/http.EncodeRequestFunc
// that encodes a getdocument request into the various portions of
// the http request (path, query, and body).
func EncodeHTTPGetDocumentOneRequest(_ context.Context, r *http.Request, request interface{}) error {
	strval := ""
	_ = strval
	req := request.(*pb.GetDocumentRequest)
	_ = req

	r.Header.Set("transport", "HTTPJSON")
	r.Header.Set("request-url", r.URL.Path)

	// Set the path parameters
	path := strings.Join([]string{
		"",
		"document",
	}, "/")
	u, err := url.Parse(path)
	if err != nil {
		return errors.Wrapf(err, "couldn't unmarshal path %q", path)
	}
	r.URL.RawPath = u.RawPath
	r.URL.Path = u.Path

	// Set the query parameters
	values := r.URL.Query()
	var tmp []byte
	_ = tmp

	values.Add("Key", fmt.Sprint(req.Key))

	values.Add("Value", fmt.Sprint(req.Value))

	r.URL.RawQuery = values.Encode()
	return nil
}

// EncodeHTTPAddDocumentZeroRequest is a transport/http.EncodeRequestFunc
// that encodes a adddocument request into the various portions of
// the http request (path, query, and body).
func EncodeHTTPAddDocumentZeroRequest(_ context.Context, r *http.Request, request interface{}) error {
	strval := ""
	_ = strval
	req := request.(*pb.AddDocumentRequest)
	_ = req

	r.Header.Set("transport", "HTTPJSON")
	r.Header.Set("request-url", r.URL.Path)

	// Set the path parameters
	path := strings.Join([]string{
		"",
		"document",
		"",
	}, "/")
	u, err := url.Parse(path)
	if err != nil {
		return errors.Wrapf(err, "couldn't unmarshal path %q", path)
	}
	r.URL.RawPath = u.RawPath
	r.URL.Path = u.Path

	// Set the query parameters
	values := r.URL.Query()
	var tmp []byte
	_ = tmp

	r.URL.RawQuery = values.Encode()
	// Set the body parameters
	var buf bytes.Buffer
	toRet := request.(*pb.AddDocumentRequest)

	toRet.Content = req.Content

	toRet.Title = req.Title

	toRet.Author = req.Author

	toRet.Topic = req.Topic

	toRet.Watermark = req.Watermark

	encoder := json.NewEncoder(&buf)
	encoder.SetEscapeHTML(false)
	if err := encoder.Encode(toRet); err != nil {
		return errors.Wrapf(err, "couldn't encode body as json %v", toRet)
	}
	r.Body = ioutil.NopCloser(&buf)
	return nil
}

// EncodeHTTPAddDocumentOneRequest is a transport/http.EncodeRequestFunc
// that encodes a adddocument request into the various portions of
// the http request (path, query, and body).
func EncodeHTTPAddDocumentOneRequest(_ context.Context, r *http.Request, request interface{}) error {
	strval := ""
	_ = strval
	req := request.(*pb.AddDocumentRequest)
	_ = req

	r.Header.Set("transport", "HTTPJSON")
	r.Header.Set("request-url", r.URL.Path)

	// Set the path parameters
	path := strings.Join([]string{
		"",
		"document",
	}, "/")
	u, err := url.Parse(path)
	if err != nil {
		return errors.Wrapf(err, "couldn't unmarshal path %q", path)
	}
	r.URL.RawPath = u.RawPath
	r.URL.Path = u.Path

	// Set the query parameters
	values := r.URL.Query()
	var tmp []byte
	_ = tmp

	values.Add("Content", fmt.Sprint(req.Content))

	values.Add("Title", fmt.Sprint(req.Title))

	values.Add("Author", fmt.Sprint(req.Author))

	values.Add("Topic", fmt.Sprint(req.Topic))

	values.Add("Watermark", fmt.Sprint(req.Watermark))

	r.URL.RawQuery = values.Encode()
	// Set the body parameters
	var buf bytes.Buffer
	toRet := request.(*pb.AddDocumentRequest)
	encoder := json.NewEncoder(&buf)
	encoder.SetEscapeHTML(false)
	if err := encoder.Encode(toRet); err != nil {
		return errors.Wrapf(err, "couldn't encode body as json %v", toRet)
	}
	r.Body = ioutil.NopCloser(&buf)
	return nil
}

// EncodeHTTPWatermarkZeroRequest is a transport/http.EncodeRequestFunc
// that encodes a watermark request into the various portions of
// the http request (path, query, and body).
func EncodeHTTPWatermarkZeroRequest(_ context.Context, r *http.Request, request interface{}) error {
	strval := ""
	_ = strval
	req := request.(*pb.WatermarkRequest)
	_ = req

	r.Header.Set("transport", "HTTPJSON")
	r.Header.Set("request-url", r.URL.Path)

	// Set the path parameters
	path := strings.Join([]string{
		"",
		"watermark",
		"",
	}, "/")
	u, err := url.Parse(path)
	if err != nil {
		return errors.Wrapf(err, "couldn't unmarshal path %q", path)
	}
	r.URL.RawPath = u.RawPath
	r.URL.Path = u.Path

	// Set the query parameters
	values := r.URL.Query()
	var tmp []byte
	_ = tmp

	r.URL.RawQuery = values.Encode()
	// Set the body parameters
	var buf bytes.Buffer
	toRet := request.(*pb.WatermarkRequest)

	toRet.TicketID = req.TicketID

	toRet.Mark = req.Mark

	encoder := json.NewEncoder(&buf)
	encoder.SetEscapeHTML(false)
	if err := encoder.Encode(toRet); err != nil {
		return errors.Wrapf(err, "couldn't encode body as json %v", toRet)
	}
	r.Body = ioutil.NopCloser(&buf)
	return nil
}

// EncodeHTTPWatermarkOneRequest is a transport/http.EncodeRequestFunc
// that encodes a watermark request into the various portions of
// the http request (path, query, and body).
func EncodeHTTPWatermarkOneRequest(_ context.Context, r *http.Request, request interface{}) error {
	strval := ""
	_ = strval
	req := request.(*pb.WatermarkRequest)
	_ = req

	r.Header.Set("transport", "HTTPJSON")
	r.Header.Set("request-url", r.URL.Path)

	// Set the path parameters
	path := strings.Join([]string{
		"",
		"watermark",
	}, "/")
	u, err := url.Parse(path)
	if err != nil {
		return errors.Wrapf(err, "couldn't unmarshal path %q", path)
	}
	r.URL.RawPath = u.RawPath
	r.URL.Path = u.Path

	// Set the query parameters
	values := r.URL.Query()
	var tmp []byte
	_ = tmp

	values.Add("TicketID", fmt.Sprint(req.TicketID))

	values.Add("Mark", fmt.Sprint(req.Mark))

	r.URL.RawQuery = values.Encode()
	// Set the body parameters
	var buf bytes.Buffer
	toRet := request.(*pb.WatermarkRequest)
	encoder := json.NewEncoder(&buf)
	encoder.SetEscapeHTML(false)
	if err := encoder.Encode(toRet); err != nil {
		return errors.Wrapf(err, "couldn't encode body as json %v", toRet)
	}
	r.Body = ioutil.NopCloser(&buf)
	return nil
}

func errorDecoder(buf []byte) error {
	var w errorWrapper
	if err := json.Unmarshal(buf, &w); err != nil {
		const size = 8196
		if len(buf) > size {
			buf = buf[:size]
		}
		return fmt.Errorf("response body '%s': cannot parse non-json request body", buf)
	}

	return errors.New(w.Error)
}

type errorWrapper struct {
	Error string `json:"error"`
}
